# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20250616-154900-lower-report

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: es

pipeline:
  - name: "WhitespaceTokenizer"
  - name: "RegexFeaturizer"
  - name: "CRFEntityExtractor"
  - name: "CountVectorsFeaturizer"
  - name: "DIETClassifier"
  - name: "FallbackClassifier"
    threshold: 0.8 # Es posible que tenga que cambiar este valor (por ahora significa que todo lo que esté por debajo de 80% de confianza, se rechazará)
    ambiguity_threshold: 0.1

policies:
  - name: "RulePolicy"
  - name: "MemoizationPolicy"
  - name: "TEDPolicy"
